name: 三和特売通知

on:
  schedule:
    # 毎日日本時間の08:00（UTC 23:00）に実行
    - cron: '0 23 * * *'
  workflow_dispatch: # 手動ボタン

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        env:
          # ここで新しい方のWebookの鍵を使います
          SANWA_WEBHOOK_URL: ${{ secrets.SANWA_WEBHOOK_URL }}
        run: python bot_grocery_sanwa.py
